"use client";
import {apiURL} from '../lib/api-url';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Globe2,Navigation,ExternalLink} from 'lucide-react';
import type * as Cesium from 'cesium';
import type {Place} from './library';
import {placeContext} from './additional-heritage';
type CesiumGlobal=typeof Cesium;
let loading:Promise<CesiumGlobal>|undefined;
function loadCesium(){if(!loading)loading=new Promise((resolve,reject)=>{const w=window as unknown as {Cesium?:CesiumGlobal;CESIUM_BASE_URL:string};if(w.Cesium){resolve(w.Cesium);return}w.CESIUM_BASE_URL='/cesium/';const css=document.createElement('link');css.rel='stylesheet';css.href='/cesium/Widgets/widgets.css';document.head.appendChild(css);const script=document.createElement('script');script.src='/cesium/Cesium.js';script.onload=()=>resolve(w.Cesium!);script.onerror=()=>{loading=undefined;reject(new Error('Could not load the globe engine.'))};document.head.appendChild(script)});return loading}
export function locationFor(place:Place){const known=placeContext[place.id];const lat=place.latitude?.trim()?Number(place.latitude):known?.lat;const lng=place.longitude?.trim()?Number(place.longitude):known?.lng;return Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat!)<=90&&Math.abs(lng!)<=180?{lat:lat!,lng:lng!,country:place.country||known?.country||''}:null}
export default function EarthView({places,initialId,onExplore}:{places:Place[];initialId?:string;onExplore:(id:string)=>void}){
 const host=useRef<HTMLDivElement>(null),viewer=useRef<Cesium.Viewer|null>(null),engine=useRef<CesiumGlobal|null>(null),detailedTiles=useRef(true);const [selected,setSelected]=useState(initialId||places.find(p=>locationFor(p))?.id||''),[mode,setMode]=useState('map'),[status,setStatus]=useState('Loading globe...'),[ready,setReady]=useState(false),[photoKey,setPhotoKey]=useState('');
 const selectedId=useRef(selected);const [placeQuery,setPlaceQuery]=useState('');
 const place=places.find(p=>p.id===selected),location=place?locationFor(place):null;
 const fly=useCallback((id:string)=>{selectedId.current=id;setSelected(id);const p=places.find(p=>p.id===id),point=p&&locationFor(p),C=engine.current,v=viewer.current;if(C&&v&&point){v.camera.setView({destination:C.Cartesian3.fromDegrees(point.lng,point.lat,detailedTiles.current?45000:1600000),orientation:{heading:0,pitch:-Math.PI/2,roll:0}});v.scene.requestRender();host.current?.setAttribute('data-camera-target',id)}},[places]);
 useEffect(()=>{let active=true;let v:Cesium.Viewer|undefined;detailedTiles.current=true;async function start(){try{const C=await loadCesium();const config=await fetch(apiURL('/api/integrations')).then(r=>r.ok?r.json():{googleMapsKey:''}).catch(()=>({googleMapsKey:''})) as {googleMapsKey:string};if(!active||!host.current)return;engine.current=C;setPhotoKey(config.googleMapsKey||'');C.Ion.defaultAccessToken='';const localMap=await C.TileMapServiceImageryProvider.fromUrl('/cesium/Assets/Textures/NaturalEarthII');if(!active)return;v=new C.Viewer(host.current,{animation:false,timeline:false,geocoder:false,baseLayerPicker:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,infoBox:false,selectionIndicator:false,fullscreenButton:false,baseLayer:new C.ImageryLayer(localMap),requestRenderMode:true,maximumRenderTimeChange:Infinity,contextOptions:{webgl:{preserveDrawingBuffer:true}}});viewer.current=v;const streets=v.imageryLayers.addImageryProvider(new C.OpenStreetMapImageryProvider({url:'https://tile.openstreetmap.org/',maximumLevel:18}));streets.imageryProvider.errorEvent.addEventListener(()=>{if(!active||!detailedTiles.current)return;detailedTiles.current=false;setStatus('Detailed street tiles are unavailable. Showing a regional map. Open Google Maps for street-level detail.');const point=locationFor(places.find(p=>p.id===selectedId.current)||places[0]);if(point)v?.camera.setView({destination:C.Cartesian3.fromDegrees(point.lng,point.lat,1600000),orientation:{heading:0,pitch:-Math.PI/2,roll:0}});v?.scene.requestRender()});v.scene.globe.baseColor=C.Color.fromCssColorString('#376d72');v.scene.screenSpaceCameraController.minimumZoomDistance=100;v.scene.renderError.addEventListener(()=>{if(active)setStatus('This browser could not render the globe. Try a browser with WebGL enabled.')});
 for(const p of places){const point=locationFor(p);if(point)v.entities.add({id:p.id,name:p.name,position:C.Cartesian3.fromDegrees(point.lng,point.lat,20),point:{pixelSize:11,color:C.Color.fromCssColorString('#c8593e'),outlineColor:C.Color.WHITE,outlineWidth:2,disableDepthTestDistance:Infinity},label:{text:p.name,font:'13px sans-serif',fillColor:C.Color.WHITE,showBackground:true,backgroundColor:C.Color.fromCssColorString('#163c32dd'),pixelOffset:new C.Cartesian2(0,-24),distanceDisplayCondition:new C.DistanceDisplayCondition(0,2500000),disableDepthTestDistance:Infinity}})}
 v.screenSpaceEventHandler.setInputAction((event:{position:Cesium.Cartesian2})=>{const picked=v!.scene.pick(event.position);if(picked?.id?.id&&places.some(p=>p.id===picked.id.id))fly(picked.id.id)},C.ScreenSpaceEventType.LEFT_CLICK);
 v.camera.setView({destination:C.Cartesian3.fromDegrees(79,22,8000000)});setReady(true);setStatus('');if(initialId){const point=locationFor(places.find(p=>p.id===initialId)!);if(point)v.camera.setView({destination:C.Cartesian3.fromDegrees(point.lng,point.lat,detailedTiles.current?45000:1600000),orientation:{heading:0,pitch:-Math.PI/2,roll:0}});v.scene.requestRender()}
 }catch{if(active)setStatus('The globe could not load. Check your connection and WebGL support.')}}void start();return()=>{active=false;setReady(false);if(v&&!v.isDestroyed())v.destroy();viewer.current=null}},[places,initialId,fly]);
 async function photorealistic(){const C=engine.current,v=viewer.current;if(!C||!v)return;if(!photoKey){setStatus('Photorealistic 3D is not connected yet. A Google Maps Map Tiles API key with billing and site coverage is required.');return}setStatus('Loading Google photographic 3D...');try{const tiles=await C.createGooglePhotorealistic3DTileset({key:photoKey,onlyUsingWithGoogleGeocoder:true},{maximumScreenSpaceError:12,cacheBytes:256*1024*1024,maximumCacheOverflowBytes:128*1024*1024});if(v.isDestroyed()){tiles.destroy();return}v.scene.primitives.add(tiles);v.imageryLayers.removeAll();v.scene.globe.show=false;setMode('photo');setStatus('Photographic coverage varies by location. Missing buildings are not reconstructed.');v.scene.requestRender();fly(selected)}catch{setStatus('Photographic 3D could not connect. Check the API key, billing and Map Tiles API permissions.')}}
 return <section className="earth-experience"><div className="earth-toolbar"><div><Globe2 size={18}/><strong>World explorer</strong><span>{mode==='photo'?'Google Photorealistic 3D':'OpenStreetMap globe'}</span></div><div><button disabled={!ready} onClick={()=>{const C=engine.current,v=viewer.current;if(C&&v)v.camera.flyTo({destination:C.Cartesian3.fromDegrees(79,22,18000000),duration:2})}} title="View the world"><Globe2 size={18}/></button>{photoKey&&mode!=='photo'&&<button disabled={!ready} onClick={photorealistic}>Photographic 3D</button>}</div></div><div className="earth-layout"><div className="earth-map"><div className="earth-canvas" ref={host}/><div className="map-controls" aria-label="Map controls"><button disabled={!ready} title="Zoom in" onClick={()=>{const v=viewer.current;if(v){v.camera.zoomIn(v.camera.positionCartographic.height*.4);v.scene.requestRender()}}}>+</button><button disabled={!ready} title="Zoom out" onClick={()=>{const v=viewer.current;if(v){v.camera.zoomOut(v.camera.positionCartographic.height*.6);v.scene.requestRender()}}}>-</button><button disabled={!ready} onClick={()=>{const v=viewer.current;if(v){v.camera.setView({orientation:{heading:0,pitch:-Math.PI/2,roll:0}});v.scene.requestRender()}}}>Top view</button><button disabled={!ready} onClick={()=>fly(selected)}>Site view</button></div></div><aside className="earth-places"><label>Find a location<input aria-label="Find map location" value={placeQuery} onChange={e=>setPlaceQuery(e.target.value)} placeholder="Place or region"/></label><div className="map-place-list">{places.filter(p=>locationFor(p)&&(p.name+' '+p.region).toLowerCase().includes(placeQuery.toLowerCase())).map(p=><button key={p.id} className={selected===p.id?'selected':''} onClick={()=>fly(p.id)}><span>{p.name}</span><small>{p.region}</small></button>)}</div><label>Fly to a place<select aria-label="Globe place" value={selected} onChange={e=>fly(e.target.value)}>{places.filter(p=>locationFor(p)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{place&&<><img src={place.image} alt={place.alt}/><span className="eyebrow">{location?.country}</span><h2>{place.name}</h2><p>{place.summary}</p>{location&&<><p className="coordinates" aria-label="Latitude and longitude">{location.lat.toFixed(5)}, {location.lng.toFixed(5)}</p><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${location.lat},${location.lng}`}><Navigation size={15}/> Open in Google Maps <ExternalLink size={14}/></a></>}<button className="primary" onClick={()=>onExplore(place.id)}>Explore this place</button></>}</aside></div><p className="earth-status" role="status">{status||'Geographic map on a 3D globe. This layer does not contain photographic buildings.'}</p></section>
}
